version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: bully-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: bully-postgres
    environment:
      POSTGRES_USER: bully_admin
      POSTGRES_PASSWORD: bully_password
      POSTGRES_DB: bully_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- NOWA BAZA DANYCH DLA WĘZŁÓW ---
  postgres_nodes:
    image: postgres:15-alpine
    container_name: bully-postgres-nodes
    environment:
      POSTGRES_USER: node_admin
      POSTGRES_PASSWORD: node_password
      POSTGRES_DB: node_db
    ports:
      - "5433:5432" # <-- KLUCZOWE: z zewnątrz łączysz się przez 5433!
    volumes:
      - pgdata_nodes:/var/lib/postgresql/data # <-- Nowy, odseparowany wolumen

  redis:
    image: redis:alpine
    container_name: aplikacja_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
  pgdata_nodes: # <-- Pamiętaj, aby dopisać ten wolumen na samym dole!