sonar.projectKey=project_bsr

# Kod źródłowy
sonar.sources=nodes,websockets_nodes,auth,database

# Poprawione ścieżki do testów (uwzględniają nadrzędny folder 'tests')
sonar.tests=tests/nodes_test,tests/websockets_nodes_test,tests/auth_test,tests/database_test

# Raporty
sonar.python.coverage.reportPaths=tests/coverage.xml
sonar.python.xunit.reportPath=tests/test-results.xml

# Konfiguracja
sonar.python.version=3.12
sonar.exclusions=**/.venv/**, **/htmlcov/**, tests/*.xml