"""Przechowuje klucze oraz typy wiadomośći do komunikacji między wątkami"""

import os

#Klucze do komunikacji między wątkami
API_ADDRESS = os.getenv("API_ADDRESS", "http://127.0.0.1:8000")
NODES_KEY = os.getenv("NODES_KEY", "KLUCZ_DO_WEZLOW!")
NODE_ID = int(os.getenv("NODE_ID", 1))

# Typy wiadomości
TYPE_MSG_ELECTION = "ELECTION"
TYPE_MSG_OK = "OK"
TYPE_MSG_COORDINATOR = "COORDINATOR"
TYPE_MSG_HEARTBEAT = "HEARTBEAT"

TYPE_DATA_NEW = "DATA_NEW"
TYPE_DATA_OK = "DATA_OK"
TYPE_DATA_OK_DELETE = "DATA_OK_DELETE"
TYPE_DATA_FAIL = "DATA_FAIL"
TYPE_DATA_DELETE = "DATA_DELETE"
TYPE_DATA_GET = "DATA_GET"

TYPE_STATUS_ACTIVE = "ACTIVE"
TYPE_STATUS_INACTIVE = "NOT_ACTIVE"